platform :ios, '10.1'
use_frameworks!

target 'Marvel' do
  pod 'SwiftHTTP'
  pod 'Gloss'
  pod 'Kingfisher'
  pod 'Arcane', git: 'https://github.com/onmyway133/Arcane'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
